name: 'Azure Deploy'
description: 'GitHub Action for deploying to Azure'
author: 'Microsoft'

inputs:
  type:
    description: ''
    required: true
  operation:
    description: ''
    required: true

  name:
    description: ''
    required: true
  location:
    description: ''
    required: true

  scope:
    description: ''
    required: true
  tenant-id:
    description: ''
    required: false
  management-group-id:
    description: ''
    required: false
  subscription-id:
    description: ''
    required: false
  resource-group-name:
    description: ''
    required: false

  template-file:
    description: ''
    required: false
  template-spec:
    description: ''
    required: false
  template-uri:
    description: ''
    required: false

  parameters-file:
    description: ''
    required: false

  what-if-exclude-change-types:
    description: ''
    required: false
    default: ''

  action-on-unmanage-resources:
    description: ''
    required: false
    default: ''
  action-on-unmanage-resourcegroups:
    description: ''
    required: false
    default: ''
  action-on-unmanage-managementgroup:
    description: ''
    required: false
    default: ''
  deny-settings-mode:
    description: ''
    required: false
    default: ''
  deny-settings-excluded-action:
    description: ''
    required: false
    default: ''
  deny-settings-excluded-principals:
    description: ''
    required: false
    default: ''
  bypass-stack-out-of-sync-error:
    description: ''
    required: false
    default: ''

  description:
    description: ''
    required: false

  tags:
    description: ''
    required: false

runs:
  using: node20
  main: dist/index.js
