name: Upload Packages

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  upload-packages:
    name: Upload Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          # Nerdbank.GitVersioning needs full git history to compute commit-height.
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies (bicep-jsonrpc)
        working-directory: ./packages/bicep-jsonrpc
        run: npm ci

      - name: Install Dependencies (bicep-deploy-common)
        working-directory: ./packages/bicep-deploy-common
        run: npm ci

      - name: Stamp version (bicep-jsonrpc)
        working-directory: ./packages/bicep-jsonrpc
        run: npm run stamp-version

      - name: Stamp version (bicep-deploy-common)
        working-directory: ./packages/bicep-deploy-common
        run: npm run stamp-version

      - name: Build bicep-jsonrpc Package
        working-directory: ./packages/bicep-jsonrpc
        run: |
          rm -Rf dist
          npm run build

      - name: Create package tarball (bicep-jsonrpc)
        id: pack-bicep-jsonrpc
        working-directory: ./packages/bicep-jsonrpc
        run: |
          packOutput=$(npm pack --json)
          echo "filename=$(echo $packOutput | jq -r '.[0].filename')" >> $GITHUB_OUTPUT
          echo "version=$(echo $packOutput | jq -r '.[0].version')" >> $GITHUB_OUTPUT

      - name: Build bicep-deploy-common Package
        working-directory: ./packages/bicep-deploy-common
        run: |
          rm -Rf dist
          npm run build

      - name: Create package tarball (bicep-deploy-common)
        id: pack-bicep-deploy-common
        working-directory: ./packages/bicep-deploy-common
        run: |
          packOutput=$(npm pack --json)
          echo "filename=$(echo $packOutput | jq -r '.[0].filename')" >> $GITHUB_OUTPUT
          echo "version=$(echo $packOutput | jq -r '.[0].version')" >> $GITHUB_OUTPUT

      - name: Reset version (bicep-jsonrpc)
        if: always()
        working-directory: ./packages/bicep-jsonrpc
        run: npm run reset-version

      - name: Reset version (bicep-deploy-common)
        if: always()
        working-directory: ./packages/bicep-deploy-common
        run: npm run reset-version

      # Using upload steps defined for the Partner Release Pipeline (https://aka.ms/azsdk/partner-release-pipeline)
      # azuresdkpartnerdrops is the managed identity that we use to upload to the partner drop folder
      - name: Login to azuresdkpartnerdrops
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURESDKPARTNERDROPS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURESDKPARTNERDROPS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURESDKPARTNERDROPS_SUBSCRIPTION_ID }}

      # Upload bicep-jsonrpc package to partner drop folder to allow external distribution under the @azure scope
      - name: Upload packages to partner drop folder
        working-directory: ./packages/bicep-jsonrpc
        run: |
          echo "Uploading ${{ steps.pack-bicep-jsonrpc.outputs.filename }} to partner drop folder at drops/bicep-jsonrpc/npm/${{ steps.pack-bicep-jsonrpc.outputs.version }}..."
          az storage blob upload -f ${{ steps.pack-bicep-jsonrpc.outputs.filename }} -c drops/bicep-jsonrpc/npm/${{ steps.pack-bicep-jsonrpc.outputs.version }} --account-name azuresdkpartnerdrops --auth-mode login
          echo "Uploading ${{ steps.pack-bicep-deploy-common.outputs.filename }} to partner drop folder at drops/bicep-deploy-common/npm/${{ steps.pack-bicep-deploy-common.outputs.version }}..."
          az storage blob upload -f ${{ steps.pack-bicep-deploy-common.outputs.filename }} -c drops/bicep-deploy-common/npm/${{ steps.pack-bicep-deploy-common.outputs.version }} --account-name azuresdkpartnerdrops --auth-mode login