name: Upload Packages

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  upload-packages:
    name: Upload Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          # Nerdbank.GitVersioning needs full git history to compute commit-height.
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Clean outputs
        run: npm run clean:packages

      - name: Stamp versions
        run: npm run stamp-version --workspace @azure/bicep-rpc-client --workspace @azure/bicep-deploy-common

      - name: Build packages
        run: npm run build:packages

      - name: Create package tarball (bicep-rpc-client)
        id: pack-bicep-rpc-client
        run: |
          packOutput=$(npm pack --workspace @azure/bicep-rpc-client --json)
          echo "filename=$(echo $packOutput | jq -r '.[0].filename')" >> $GITHUB_OUTPUT
          echo "version=$(echo $packOutput | jq -r '.[0].version')" >> $GITHUB_OUTPUT

      - name: Create package tarball (bicep-deploy-common)
        id: pack-bicep-deploy-common
        run: |
          packOutput=$(npm pack --workspace @azure/bicep-deploy-common --json)
          echo "filename=$(echo $packOutput | jq -r '.[0].filename')" >> $GITHUB_OUTPUT
          echo "version=$(echo $packOutput | jq -r '.[0].version')" >> $GITHUB_OUTPUT

      - name: Reset versions
        if: always()
        run: npm run reset-version --workspace @azure/bicep-rpc-client --workspace @azure/bicep-deploy-common

      # Using upload steps defined for the Partner Release Pipeline (https://aka.ms/azsdk/partner-release-pipeline)
      # azuresdkpartnerdrops is the managed identity that we use to upload to the partner drop folder
      - name: Login to azuresdkpartnerdrops
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURESDKPARTNERDROPS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURESDKPARTNERDROPS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURESDKPARTNERDROPS_SUBSCRIPTION_ID }}

      # Upload packages to partner drop folder to allow external distribution under the @azure scope
      - name: Upload packages to partner drop folder
        run: |
          echo "Uploading ${{ steps.pack-bicep-rpc-client.outputs.filename }} to partner drop folder at drops/bicep-rpc-client/npm/${{ steps.pack-bicep-rpc-client.outputs.version }}..."
          az storage blob upload -f ${{ steps.pack-bicep-rpc-client.outputs.filename }} -c drops/bicep-rpc-client/npm/${{ steps.pack-bicep-rpc-client.outputs.version }} --account-name azuresdkpartnerdrops --auth-mode login
          echo "Uploading ${{ steps.pack-bicep-deploy-common.outputs.filename }} to partner drop folder at drops/bicep-deploy-common/npm/${{ steps.pack-bicep-deploy-common.outputs.version }}..."
          az storage blob upload -f ${{ steps.pack-bicep-deploy-common.outputs.filename }} -c drops/bicep-deploy-common/npm/${{ steps.pack-bicep-deploy-common.outputs.version }} --account-name azuresdkpartnerdrops --auth-mode login